# Generated by Django 2.2 on 2020-08-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('email', models.TextField()),
                ('subscribe_dataset_number', models.CharField(max_length=20)),
                ('subscribe_city', models.CharField(max_length=20)),
                ('api_token', models.CharField(max_length=255)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_list',
            },
        ),
    ]
